import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {loadCurrent} from '../assets/loader.mjs';import {emptySeason} from '../assets/core.mjs';import {publishLocal} from '../tools/publish.mjs';import {checksum,readJSON,published} from '../tools/files.mjs';import {fixture} from './fixtures.mjs';
const memoryCache=()=>{const values=new Map();return {open:async()=>({put:async(k,v)=>values.set(String(k),v.clone()),match:async k=>values.get(String(k))?.clone()}),values};};
const responseSet=data=>{const bytes=Buffer.from(JSON.stringify(data)),manifest={schemaVersion:1,file:'data/releases/test.json',sha256:checksum(bytes),updatedAt:data.updatedAt};return {bytes,manifest,fetcher:async url=>new Response(String(url).endsWith('manifest.json')?JSON.stringify(manifest):bytes)};};
test('loader verifies hash and schema at a GitHub Pages subpath',async()=>{const response=responseSet(emptySeason()),paths=[];const result=await loadCurrent({fetcher:async(url,opts)=>{paths.push(String(url));assert.equal(opts.cache,'no-store');return response.fetcher(url);},cacheStorage:memoryCache(),base:'https://example.test/NBA-Fantasy-Stats-Tracker/'});assert.equal(result.state,'fresh');assert.ok(paths.every(p=>p.startsWith('https://example.test/NBA-Fantasy-Stats-Tracker/data/')));});
test('network failure, malformed data, bad hash and HTTP errors retain last verified snapshot',async()=>{const cacheStorage=memoryCache(),base='https://test.local/project/',response=responseSet(fixture());await loadCurrent({fetcher:response.fetcher,cacheStorage,base});for(const fetcher of [async()=>{throw new Error('offline');},async()=>new Response('{}'),async()=>new Response('not json'),async()=>new Response('{}',{status:500}),async url=>String(url).endsWith('manifest.json')?new Response(JSON.stringify(response.manifest)):new Response('{}')]){const result=await loadCurrent({fetcher,cacheStorage,base});assert.equal(result.state,'cached');assert.equal(result.data.lines.length,3);}});
test('cold offline load is explicitly unavailable with zero fabricated rows',async()=>{const result=await loadCurrent({fetcher:async()=>{throw new Error('offline');},cacheStorage:memoryCache(),base:'https://example.test/'});assert.equal(result.state,'unavailable');assert.equal(result.data.connection,'not-connected');assert.equal(result.data.lines.length,0);});
test('invalid JSON schema with valid hash never replaces cached data',async()=>{const cacheStorage=memoryCache(),base='https://test.local/';await loadCurrent({fetcher:responseSet(fixture()).fetcher,cacheStorage,base});const invalid=fixture();invalid.lines.push(invalid.lines[0]);const result=await loadCurrent({fetcher:responseSet(invalid).fetcher,cacheStorage,base});assert.equal(result.state,'cached');assert.equal(result.data.lines.length,3);});
test('local publication is immutable, retains previous manifest and validates before switching',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'nba-fantasy-test-'));try{const first=await publishLocal(emptySeason(),{root});const second=await publishLocal(fixture(),{root});assert.notEqual(first.file,second.file);assert.deepEqual(await readJSON(path.join(root,'data/manifest.previous.json')),first);assert.equal((await published(root)).lines.length,3);const invalid=fixture();invalid.lines.push(invalid.lines[0]);await assert.rejects(publishLocal(invalid,{root}));assert.deepEqual(await readJSON(path.join(root,'data/manifest.json')),second);await fs.access(path.join(root,first.file));}finally{await fs.rm(root,{recursive:true});}});
