import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs/promises';
const source=await fs.readFile('sw.js','utf8');
function setup({offline=false,legacy=false}={}){
  const events={},stored=new Map(),deleted=[],navigated=[];
  const cache={addAll:async list=>list.forEach(x=>stored.set(new URL(x,'https://test.local/project/').href,new Response('cached '+x))),put:async(req,res)=>stored.set(typeof req==='string'?req:req.url,res.clone()),match:async req=>stored.get(typeof req==='string'?req:req.url)?.clone()};
  const self={registration:{scope:'https://test.local/project/'},skipWaiting:async()=>{},clients:{claim:async()=>{},matchAll:async()=>[{url:'https://test.local/project/',navigate:async u=>navigated.push(u)},{url:'https://test.local/other/',navigate:async u=>navigated.push(u)}]},addEventListener:(name,fn)=>events[name]=fn};
  vm.runInNewContext(source,{self,caches:{open:async()=>cache,keys:async()=>legacy?['nbafs-shell-v1','nbafs-data-v1','unrelated','nbafs-verified-v2']:['nbafs-shell-v2'],delete:async k=>deleted.push(k)},URL,Response,AbortSignal,fetch:async()=>{if(offline)throw new Error('offline');return new Response('fresh');}});
  return {events,stored,deleted,navigated,run:async(name)=>{let promise;events[name]({waitUntil:p=>promise=p});await promise;},fetch:async(url,mode='cors')=>{let response;events.fetch({request:{method:'GET',url,mode},respondWith:p=>response=p});return response?await response:null;}};
}
test('PWA v1 migration removes only app caches and refreshes only its own scope',async()=>{const s=setup({legacy:true});await s.run('activate');assert.deepEqual(s.deleted,['nbafs-shell-v1','nbafs-data-v1']);assert.deepEqual(s.navigated,['https://test.local/project/']);});
test('PWA shell is network-first and serves cached navigation offline at a Pages subpath',async()=>{const fresh=setup();await fresh.run('install');assert.equal(await (await fresh.fetch('https://test.local/project/','navigate')).text(),'fresh');const offline=setup({offline:true});await offline.run('install');assert.match(await (await offline.fetch('https://test.local/project/','navigate')).text(),/cached/);assert.match(await (await offline.fetch('https://test.local/project/assets/boot.mjs')).text(),/cached/);});
test('PWA does not intercept current data manifests, release errors or external origins',async()=>{const s=setup();assert.equal(await s.fetch('https://test.local/project/data/manifest.json'),null);assert.equal(await s.fetch('https://test.local/project/data/releases/release.json'),null);assert.equal(await s.fetch('https://other.local/project/'),null);});
