import test from 'node:test';import assert from 'node:assert/strict';import {editorBusy,readDraft,createAppUpdates} from '../assets/updates.mjs';
const scope='https://test.local/project/',key='nbafs.update.draft:'+scope,guard='nbafs.update.reload:'+scope;
const tick=()=>new Promise(resolve=>setTimeout(resolve,15));
function fixture({blocked=false,previous=true,draft=null}={}){
  const dom=new Map(),values=new Map(draft?[[key,JSON.stringify(draft)]]:[]);let time=100000,reloads=0,checks=0,captured=0,restored=null,posted=0;
  const win=new EventTarget(),doc=new EventTarget(),sw=new EventTarget();
  const node=()=>({hidden:false,textContent:'',setAttribute(){},append(){}});
  Object.assign(doc,{baseURI:scope,visibilityState:'visible',body:{append(n){dom.set(n.id,n);}},createElement:node,getElementById:id=>dom.get(id),activeElement:null});
  const worker=version=>({postMessage(message,ports){if(message.type==='GET_APP_VERSION')ports[0].postMessage({version});else posted++;},addEventListener(){}});
  const old=worker('a'),next=worker('b'),reg=new EventTarget();Object.assign(reg,{waiting:null,installing:null,update:async()=>{checks++;}});
  Object.assign(sw,{controller:previous?old:null,register:async(url,options)=>{assert.equal(url,scope+'sw.js');assert.equal(options.updateViaCache,'none');return reg;}});
  const storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>{if(blocked)throw Error('quota');values.set(k,v);},removeItem:k=>values.delete(k)};
  Object.assign(win,{location:{protocol:'https:',reload(){reloads++;}},sessionStorage:storage,setTimeout:()=>1,setInterval:()=>1,FantasySession:{capture(){captured++;return {page:'data',controls:[{id:'w-pts',value:'3'}]};},async restore(s){restored=s;}}});
  const nav={serviceWorker:sw,onLine:true},app=createAppUpdates({win,doc,nav,storage,now:()=>time});
  return {app,win,doc,nav,sw,reg,values,next,advance:()=>{time+=40000;},async changed(){sw.controller=next;sw.dispatchEvent(new Event('controllerchange'));await tick();},get reloads(){return reloads;},get checks(){return checks;},get captured(){return captured;},get restored(){return restored;},get posted(){return posted;}};
}
test('only edited focused controls delay automatic updates',()=>{const edited={matches:()=>true},untouched={matches:()=>true},touched=new WeakSet([edited]);assert.equal(editorBusy(edited,touched),true);assert.equal(editorBusy(untouched,touched),false);assert.equal(editorBusy(null,touched),false);});
test('drafts are limited to the same app scope and thirty minutes',()=>{const item={schema:1,scope,at:100,state:{}};const storage={getItem:()=>JSON.stringify(item)};assert.ok(readDraft(storage,key,scope,101));assert.equal(readDraft(storage,key,scope+'other',101),null);assert.equal(readDraft(storage,key,scope,1800101),null);assert.equal(readDraft({getItem:()=>'{broken'},key,scope),null);});
test('controller changes wait for startup, save the view, then reload at most once',async()=>{const f=fixture();await tick();await f.changed();assert.equal(f.reloads,0);await f.app.ready();assert.equal(f.reloads,1);assert.equal(f.captured,1);assert.equal(JSON.parse(f.values.get(key)).state.controls[0].value,'3');await f.changed();assert.equal(f.reloads,1);assert.equal(f.values.get(guard),'b');});
test('first service-worker installation does not reload the first visit',async()=>{const f=fixture({previous:false});await tick();await f.app.ready();await f.changed();assert.equal(f.reloads,0);});
test('updates preserve a pending edit and activate only after an explicit choice',async()=>{const f=fixture();await tick();await f.app.ready();const input={matches:()=>true};f.doc.activeElement=input;const event=new Event('input');Object.defineProperty(event,'target',{value:input});f.doc.dispatchEvent(event);f.reg.waiting=f.next;await f.app.check();assert.equal(f.posted,0);assert.equal(f.reloads,0);await f.app.updateNow();assert.equal(f.posted,1);assert.equal(f.reloads,0);await f.changed();assert.equal(f.reloads,0);f.doc.activeElement=null;f.advance();f.win.dispatchEvent(new Event('focus'));await tick();assert.equal(f.reloads,1);});
test('unavailable draft storage prevents automatic activation and reload',async()=>{const f=fixture({blocked:true});await tick();await f.app.ready();f.reg.waiting=f.next;await f.app.check();await f.app.updateNow();assert.equal(f.posted,0);await f.changed();assert.equal(f.reloads,0);});
test('successful startup restores a draft once and leaves persistent scoring untouched',async()=>{const state={page:'trades',trade:{left:[2544],right:[]}},f=fixture({draft:{schema:1,scope,at:99999,state}});f.values.set('nbafs.scoring','custom');await f.app.ready();assert.deepEqual(f.restored,state);assert.equal(f.values.has(key),false);assert.equal(f.values.get('nbafs.scoring'),'custom');});
test('a per-version guard prevents repeated reloads even after a new app instance',async()=>{const f=fixture();f.values.set(guard,'b');await tick();await f.app.ready();await f.changed();assert.equal(f.reloads,0);});
test('focus and reconnection check updates, with offline, hidden and repeated checks suppressed',async()=>{const f=fixture();await tick();const start=f.checks;f.advance();f.nav.onLine=false;await f.app.check();f.nav.onLine=true;f.doc.visibilityState='hidden';await f.app.check();assert.equal(f.checks,start);f.doc.visibilityState='visible';f.win.dispatchEvent(new Event('focus'));await tick();assert.equal(f.checks,start+1);f.win.dispatchEvent(new Event('focus'));await tick();assert.equal(f.checks,start+1);f.advance();f.win.dispatchEvent(new Event('online'));await tick();assert.equal(f.checks,start+2);});
